### ISSUE TITLE
Tightly connected components

### ISSUE THREAD

**Issue by vporton** [ets-labs/python-dependency-injector#186]
I my application there is class `AssetParser` which unsurprisingly extracts data from an asset file.

`AssetParser` calls some sub-parsers such as `NamespacesParser` and `TransformersParser`.

I am going to create a provider for creating `AssetParser` object.

Question: Does it make sense to create providers for sub-parsers (such as `NamespacesParser` and `TransformersParser`)? These components are tightly coupled with `AssetParser` and are not going to be used anywhere except that in implementation of `AssetParser`. Second question: Should `AssetParser` object create `NamespacesParser` and `TransformersParser` through providers or directly calling constructors?

**Comment by vporton** [comment]
Well, I think that the theory is that one should create providers even in the case of such tight coupling (for example, to ease testing).

But are there any reason that `AssetParser` should use these providers for `NamespacesParser` and `TransformersParser` rather than to call the constructors directly?

**Comment by rmk135** [comment]
Hi Victor,

Will take a look during the day.

Thanks,
Roman

**Comment by vporton** [comment]
A related question: Should I dependency-inject `NamespacesParser` and `TransformersParser` into `AssetParser`?

They are tightly coupled components, and it is unlikely that we will ever need `AssetParser` using other subparsers. So it looks like that dependency injection here is unnecessary. Or do I miss the idea?

**Comment by vporton** [comment]
What's about defining a provider of `NamespacesParser` (in order to easily switch between factory provider and singleton provider), but call the provider directly from `AssetParser` instead of dependency injection (because I find no reason to use dependency injection)?

**Comment by rmk135** [comment]
Hi Victory,

Sorry for delay in response, I will try to answer questions one-by-one, so:

---

> Question: Does it make sense to create providers for sub-parsers (such as `NamespacesParser` and `TransformersParser`)?

It mostly depends on 3 things:

1. Are `NamespacesParser` and `TransformersParser` used anywhere else? If not, don't create providers for them.
2. Do `NamespacesParser` and `TransformersParser` have their own dependencies? If yes, create providers for them.
3. What granularity of structure details you want to see? If you want to see every single component, then create provider for it.

---

> Second question: Should AssetParser object create `NamespacesParser` and `TransformersParser` through providers or directly calling constructors?
> But are there any reason that AssetParser should use these providers for NamespacesParser and TransformersParser rather than to call the constructors directly?

`NamespacesParser` and `TransformersParser` should have their own providers if:

1. They are used in other places.
2. They have their own dependencies.

---

> Should I dependency-inject `NamespacesParser` and `TransformersParser` into `AssetParser`?

Good question. I don't know your architecture, but it seems that you should inject them because they are "important" parts of the `AssetParser`. However, meaning of word "important" can vary from project to project. Objective reasons for using providers are the same:

1. They are used in other places.
2. They have their own dependencies.

I, typically, tend to use providers even in simple cases to follow consistent approach, but I often don't use providers for exceptions.

---

> What's about defining a provider of `NamespacesParser` (in order to easily switch between factory provider and singleton provider), but call the provider directly from `AssetParser` instead of dependency injection (because I find no reason to use dependency injection)?

It's possible, but it will not be dependency injection anymore. I loved this explanation (http://python-dependency-injector.ets-labs.org/introduction/what_is_di.html#best-explanation-ever):

Question:

> How to explain dependency injection to a 5-year-old?

Answer:

> When you go and get things out of the refrigerator for yourself, you can cause problems. You might leave the door open, you might get something Mommy or Daddy doesn’t want you to have. You might even be looking for something we don’t even have or which has expired. **What you should be doing is stating a need**, “I need something to drink with lunch,” **and then** we will **make sure you have something** when you sit down to eat.

---

Making a conclusion,

I would recommend to make a decision on creating or not creating separate providers for `NamespacesParser` and `TransformersParser` based on answer to question: are `NamespacesParser` and `TransformersParser` "important, sensible" parts of your architecture. If these things are more implementation details and they don't have any external dependencies, then it might have sense to don't create separate providers for them.

I also would recommend to dependency-inject `NamespacesParser` and `TransformersParser` into `AssetParser` not depending on "providers" question. The only exception is that you still treat them like something very minor, like exception.

---

Thanks,
Roman

**Comment by rmk135** [comment]
Hi @vporton , I'm closing this question. Hope that my answer made things just a bit more clear. Please, let me know if any other help is needed.

Thank you,
Roman
