### ISSUE TITLE
Issue resetting ThreadLocalSingletons

### ISSUE THREAD

**Issue by jeroenrietveld** [ets-labs/python-dependency-injector#217]
Hi!

I'm running into an issue with resetting a ThreadLocalSingleton.
When I call `reset` on the provider, I expect the next `_provide` to return a new instance of the specified type.

However, as can been seen in this excerpt of the code:
```
cdef class ThreadLocalSingleton(BaseSingleton):
    ...

    def reset(self):
        self.__storage.instance = None

    cpdef object _provide(self, tuple args, dict kwargs):
        cdef object instance

        try:
            instance = self.__storage.instance
        except AttributeError:
            instance = __factory_call(self.__instantiator, args, kwargs)
            self.__storage.instance = instance
        finally:
            return instance
```

When `reset` is called, it sets the `__storage.instance` to `None`.
However, when the `_provide` method is called, it returns the instance, unless the attribute is not present. In other words, after a `reset`, a new instance will never be initialized, because the attribute is present, so no `AttributeError` will be raised.

Am I approaching this correctly, or should the `instance` attribute actually be deleted?

Thanks!

**Comment by jeroenrietveld** [comment]
If this is indeed unintended behaviour I can create a PR!

**Comment by rmk135** [comment]
Hi @jeroenrietveld ,

Yeah, I think you're absolutely right - it's a bug. It definitely should be fixed and I would really appreciate if you can take this initiate.

Unfortunately, I don't have documentation for contributions / development environment setup for Dependency Injector, but I can give a quick tour how you could deal with it. So, 1st thing is that you need to setup is development environment - for Dependency Injector I use just `virtualenv`. Python version does not matter to much, but I currently use 3.7. Then you need to setup development dependencies. You can do this using `requirements-dev.txt`. After this is done you can just try to run `make test-py2` and / or `make test-py3`. Actually, passing of any tests subset is fine, because it does not look like issue related some particular Python versions. We also would do final testing on TravisCI before merge.

You're also welcome to add test for this particular bug. I think that the right place for this is - https://github.com/ets-labs/python-dependency-injector/blob/master/tests/unit/providers/test_singletons_py2_py3.py#L387

Last thing is about Pull Request - when you will be creating it - please, make pull request to `develop` branch.

Regards,
Roman

**Comment by jeroenrietveld** [comment]
Hi @rmk135,

Thanks for your response!
I created a PR with the bug fix.

Let me know if you would like to see something differently.

**Comment by rmk135** [comment]
PR is merged, awesome job, thank you!

I've pushed new release to PyPi, it is 3.14.5.

PS: I've also added you to the list of contributors - https://github.com/ets-labs/python-dependency-injector/blob/master/CONTRIBUTORS.rst

Thank you again,
Best regards,
Roman

**Comment by jeroenrietveld** [comment]
No, thank you, for your work on this!
Great that it's on PyPi already :)

Best regards,
Jeroen
