### ISSUE TITLE
Name conventional

### ISSUE THREAD

**Issue by martinmamdouh** [ets-labs/python-dependency-injector#224]
I think naming Factory method is not accurate as it is not a factory as much as it is prototype because it always returns a copy instance from the same class.

**Comment by rmk135** [comment]
Hi @martinmamdouh ,

Can you, please, provide more details about what you suggest to rename?

PS: I'm terribly sorry for late response.

Thanks,
Roman

**Comment by martinmamdouh** [comment]
Hi Roman,
Firstly I would like to thank you for this awsome package, but what I have noticed is that:
To inside the IOC provider we have to decide either to create a singleton instance of a class so every time the provider will inject any client with the same instance or using a factory which means everytime the provider will inject the client with a new instance from the same class, But from my point of view here we are using a prototype pattern not a factory pattern because it always return a clone of the same class or instance from the same exact class as we used 'new' verb in any other programming language 
But factory as per wiki returns objects of 'varying prototype'.
Wiki:
""In object-oriented programming (OOP), a factory is an object for creating other objects – formally a factory is a function or method that returns objects of a varying prototype or class from some method call"" 

while prototype is:
 ""The prototype pattern is a creational design pattern in software development. It is used when the type of objects to create is determined by a prototypical instance, which is cloned to produce new objects. This pattern is used to:

avoid subclasses of an object creator in the client application, like the factory method pattern does.""
Thanks
Martin

**Comment by rmk135** [comment]
Hi Martin,

I think that there is a little confusion in terms of terminology, so let me try to clarify how it looks to me.

`Factory` is a callable that returns new instance of some class. `Factory` provider in Dependency Injector is done exactly for that:

```python
user_factory = providers.Factory(User)
user_1 = user_factory()
user_2 = user_factory()
assert user_1 is not user_2
```

Can such `Factory` support varying of the class? Of course! It's done using "overriding" feature:

```python
user_factory = providers.Factory(User)
user_1 = user_factory()

user_factory.override(providers.Factory(OtherUser))
user_2 = user_factory()

assert user_1 is not user_2
assert isinstance(user_1, User)
assert isinstance(user_2, OtherUser)
```

That's a power of `Factory`. You start with something and you can override later.

Now let's talk about `Prototype`. That's how wikipedia defines prototype pattern:

> The prototype pattern is a creational design pattern in software development. It is used when the type of objects to create is determined by a prototypical instance, which is cloned to produce new objects.

Special attention to **prototypical instance**. Consider next example of prototype pattern:

```python
def create_prototype(prototype):
    def clone_prototype():
        return deepcopy(prototype)
    return clone_prototype

user_prototyper = create_prototype(User())

user_1 = user_prototyper()
user_2 = user_prototyper()

assert user_1 is not user_2
```

At this point, let's add one more statement that will demonstrate very important difference between factory and prototype - let's assume that we need to specify user id once user is created. With `Factory` this is pretty straightforward:

```python
user_factory = providers.Factory(User)
user_1 = user_factory(id=1)
user_2 = user_factory(id=2)
assert user_1.id == 1
assert user_2.id == 2
```

What's about prototype? It's not so obvious know. While prototype pattern is based on **prototypical instance**, this instance should be put to prototyper in intermediate state and post-configured after copying was done:

```python
def create_prototype(prototype):
    def clone_prototype(*args, **kwargs):
        clone = deepcopy(prototype)
        clone.post_configure(*args, **kwargs)
        return clone
    return clone_prototype

user_prototyper = create_prototype(User())

user_1 = user_prototyper(id=1)
user_2 = user_prototyper(id=2)

assert user_1 is not user_2
```

I see there 4 import points:

1. `User` class must degrade to support intermediate state to be used with prototyper
2. `User` class and framework code (`create_prototype()`) should be dependent on each other through `clone.post_configure` call
3. `User` instance should be created in declarative phase
4. There is no guarantee that it's safe enough to `copy` / `deepcopy` instance of `User` class

Basically, there is no `Prototype` provider because of these reasons - Dependency Injector is built on idea that dependency injection framework should not pollute your code - it should be put upon your code.

Other side of the question is that I do like `Prototype` pattern for some cases and the way you could use it with Dependency Injector is next:

```python
def create_prototype(prototype):
    def clone_prototype():
        return deepcopy(prototype)
    return clone_prototype

user_factory = providers.Factory(create_prototype(User()))

user_1 = user_factory()
user_2 = user_factory()

assert user_1 is not user_2
```

Talking about `Singleton` - it's also kind of different animal. Everything above is also true about `Singleton` with the only reason that it save the instance after first creation. Prototype and `Singleton` both hold reference instance internally, but for different reasons - prototype clones it, singleton just returns. `Factory` holds class internally, but it doesn't _returns a copy instance from the same class_, it returns **new instance of the same class** and context parameters (remember example with `id`) make these instances unique.

Dependency Injector was created to be a tool for supporting supple design. All providers are designed with interchangeability in mind, and the key to this interchangeability is `provider.override(provider)` feature.

Making a summary, I'm not sure there is a need to rename `Factory` or `Singleton` providers. Talking about `Prototype` pattern - I do like it, but adding provider for it in Dependency Injector will complicate things a lot and ruin some of concept ideas. I do like and use it sometimes, but I do appreciate it's not to be implemented as a part of Dependency Injector.

Thanks,
Roman

**Comment by rmk135** [comment]
@martinmamdouh ,

I'll close this issue, but feel free to re-open in case you would appreciate to discuss it more.

I'm so grateful to you for bringing up this question - I do hope that we together would build a new era of Python programming paradigms that would respect supple design & inversion of control.

Thanks,
Roman
