### ISSUE TITLE
Import containers failed when built with nuitka

### ISSUE THREAD

**Issue by lauevrar77** [ets-labs/python-dependency-injector#238]
Hi, 

I have an ImportError when I try to run my (compiled with nuitka) application.
It gives me an : 
```
from dependency_injector import containers, providers
ImportError: cannot import name 'containers'
```

However, everything works perfectly when running with standard python3.6 interpreter. 

Here is my compilation command: 
`python3 -m nuitka --follow-imports app.py`

Do you have some hints on how to make this work ?

**Comment by rmk135** [comment]
Hi @lauevrar77 ,

I'll try to run it locally and see if I have any guess.

**Comment by lauevrar77** [comment]
Hi @rmk135 ,

Have you found any hint for me ?

**Comment by rmk135** [comment]
No, I’m sorry, didn’t look on it yet. I’ll take a look later today.

Thanks,
Roman

**Comment by rmk135** [comment]
Have you tried `--standalone` option?

<img width="1172" alt="Screen Shot 2019-12-15 at 10 38 09 PM" src="https://user-images.githubusercontent.com/1742049/70877490-a1947e00-1f8b-11ea-81bf-e580923dc3c5.png">

The thing is that `Dependency Injector` is distributes as C extension, so probably that's why it could not be import after `nuitka` compilation.

**Comment by rmk135** [comment]
Closing this issue.
