### ISSUE TITLE
Newbie question: Why is there a Delegate Factory?

### ISSUE THREAD

**Issue by garyrob** [ets-labs/python-dependency-injector#246]
Hello, I'm an experienced Python coder, but new to dependency injection and this library in particular. At the link location: http://python-dependency-injector.ets-labs.org/providers/factory.html#factory-providers-delegation, there's an example of using a providers.Delegate(). 

At line 27, we have:

    photos_factory=providers.Delegate(photos_factory))

However, if I replace that with:

    photos_factory=photos_factory

and run the code, I get exactly the same results. The asserts at the end, which test for userx.main_photo,  pass either way. So why do I need to use providers.Delegate(photos_factory)?

This question is an "issue" in the sense that I think that, unless I missed something very obvious, which is certainly possible, the docs could be improved to address this question more effectively. In particular, an example that failed if providers.Delegate(photos_factory) was replaced with photo_factory might be helpful.

**Comment by rmk135** [comment]
Hi Gary,

Take a look on the screenshot:

<img width="1680" alt="Screen Shot 2020-04-26 at 10 05 32 PM" src="https://user-images.githubusercontent.com/1742049/80327619-c1299600-880a-11ea-8c77-573ceee9de1d.png">

There two pieces of that puzzle:

1. There are 3 different options how one can use the feature. They are in the red rectangles (lines 27-30, 32-37, and 40-44).
2. Factories at all 3 options have same names. See blue underlining.

You do changes to 2nd option. These changes are messed up by 3rd option. Asserts are executed with factories from the 3rd option. That's why you don't see any effect from your changes.

I've created a confusion when I gave factories the same names at all 3 options. My apologies so you had to run through that. I will improve this example.

Thank you for raising this. Please, open an issue in case you need help or find anything else could be improved.

Best Regards,
Roman

**Comment by garyrob** [comment]
Thanks so much for the kindness and patience with which you responded to my question. It is very much appreciated. I should have examined the code more carefully!!
