### ISSUE TITLE
A service becomes a _asyncio.Future if it has an asynchronous dependency

### ISSUE THREAD

**Issue by gtors** [ets-labs/python-dependency-injector#393]
di version: 4.20.2
python: 3.9.1
os: linux

```python
from dependency_injector import containers, providers

async def init_resource():
    yield ...

class Service:
    def __init__(self, res):
        ...

class AppContainer(containers.DeclarativeContainer):
    res = providers.Resource(init_resource)
    foo = providers.Singleton(Service, res)
    bar = providers.Singleton(Service, None)

container = AppContainer()

foo = container.foo()
print(type(foo))  # <class '_asyncio.Future'> <-- why not a <class '__main__.Service'> instance?

bar = container.bar()
print(type(bar))   # <class '__main__.Service'>
```

It's bug or feature? Maybe I miss something in documentation?

**Comment by rmk135** [comment]
Hi @gtors ,

It's not a bug. `container.foo()` returns future because it has async dependency.

See https://python-dependency-injector.ets-labs.org/providers/async.html#async-injections
<img width="681" alt="Screenshot 2021-02-09 at 13 26 49" src="https://user-images.githubusercontent.com/1742049/107409943-aba40500-6ada-11eb-8c6d-34aa462ae99d.png">

**Comment by gtors** [comment]
Oops, I missed it. Thanks for the quick answer!

**Comment by rmk135** [comment]
No problems. In case you need any other help - you're welcome.
