### ISSUE TITLE
Current Maintenance Status and Future Plans

### ISSUE THREAD

**Issue by moccajoghurt** [ets-labs/python-dependency-injector#791]
Hello, 

I'm considering integrating this library into my project but noticed the last update was two years ago. Could you confirm if the repository is still maintained and if it's safe to use in terms of security and compatibility? 

Thank you for your work on this project and for any information you can provide.

**Comment by jasonprado** [comment]
I am using it in production for a medium-sized project and it's been a mostly positive experience, but the lack of maintenance has unfortunately made me switch to [injector](https://github.com/python-injector/injector) for another new project. Small problems are accruing, like only supporting pydantic v1 and no support for Python 3.12. There are PRs for addressing these issues, so I feel like a fork would be successful.

**Comment by jonathangreen** [comment]
There are a couple other issues open with a similar question: https://github.com/ets-labs/python-dependency-injector/issues/742, https://github.com/ets-labs/python-dependency-injector/issues/763.

In https://github.com/ets-labs/python-dependency-injector/issues/742#issuecomment-1812652596 @rmk135 did respond on Nov 15, 2023, but no response since then. That does make me concerned for the future of this project.

**Comment by benm5678** [comment]
New to python, it's a bit odd to me such a popular language has no good DI framework... this one is the closest, but some issues popping up and no one to support it.  It can always be forked I suppose if there were enough that wanted & are able to support it.  Makes me wonder about python usage in large projects...or perhaps there are alternate approaches that explain the lack of options here.

**Comment by RubenRibGarcia** [comment]
It is a bit sad to let this library to be left like this 😕. I know that a fork was already done, at least to give support to Python 3.12. That said are't we able, as a community, to fork this project and start from there ? 

Probably we would "only" need to find a quorum for this to work.

**Comment by dcendents** [comment]
I've successfully switched to https://github.com/kodemore/kink, it has all the functionalities I need and the implementation is much simpler, so it if gets abandoned I could just maintain the code myself in the project...

**Comment by Guibod** [comment]
I’ve switched to `injector`.

**Comment by ngirard** [comment]
Hey @Guibod ,
how is the switch going so far ? Would you mind elaborating a bit ?
Thanks !

**Comment by Guibod** [comment]
@ngirard 
Well, as you noticed, pdi is pretty complex and use advanced pattern, such as the ressource instance type, with its delayed cleanup through generators. Sometimes it’s pretty magic or even cryptic. 

On the other side, `injector` is a dumb and very basic injector. The team in charge of the project seems pretty reluctant to add advanced features. 

A good example is their proposal for our `ResourceProvider`. The ressource cleanup pattern is detailed in an extra documentation  that is awaiting to be merged (see the [PR](https://github.com/python-injector/injector/pull/252)). So that’s doable, but with extra legwork.

In short:
- If you have basic needs, go for injector.
- If you need something well polished, or with advanced patterns support, don’t go (yet), that’s a work in progress
- If you are ready to implement some extra layers, you can mostly achieve anything.
- Kink and Injector are pretty similar as far as I can tell. I’ve follow the crowd on the most popular one.

In detail:
- Injector is simple, and use annotation, that’s great
- Injector does not provide static injector, so each top level instance must define its own injector
- Injector relies on types to identify dependencies, so you need to annotate or `NewType` your instance of string. I found that neat.
- Injector is messy if you have a nullable instance (because you cannot `NewType("my-type", None)`)
- Injector is messy in conjunction of mypy if you have multiples types for the same dependency slot that does not share parent class. For instance returning either str or `FilePath`.
- Documentation is lacking many examples, and clarification. But since the tool is very basic, you can learn pretty quickly.
- I’ve stumbled on a python 3.8 to 3.9 bug in conjunction of `pydantic-settings` that [i’ve documented there](https://github.com/python-injector/injector/issues/253).
- Only the `SingletonScope` is supported, but there are request for `SessionScope`
- Configuration is not supported as a feature, which is better if you are using `Pydantic-settings` after all.
- There is no proper support for `CallableProvider`, but you can access a value that run your routine and return `None`. Which is less that ideal.

You can see my migration in action there (unfortunately i’ve renamed some files so my « container » file cannot be diff simply):
- [The new container definition](https://github.com/Guibod/mightstone/commit/79ddd90290603261fcfca7deea0574c287241bb2#diff-aacd52c7ec429964ecbc2d2d7b6a5ac93aae5ba50de720980a7b6cb6841c4eea) witth injector
- [The old container definition](https://github.com/Guibod/mightstone/commit/79ddd90290603261fcfca7deea0574c287241bb2#diff-60f6baa1399b05b2723ef7c38d9b66f9ccd49c8d8fce204d60af2c93ea89a311) with PDI

**Comment by ngirard** [comment]
Wow... thank you so much @Guibod !
Much appreciated !

**Comment by JobaDiniz** [comment]
> I know that a fork was already done, at least to give support to Python 3.12

@RubenRibGarcia what's the fork link?

**Comment by RubenRibGarcia** [comment]
It seems @rmk135 merged a PR to support Python 3.12 😄 .

Which is kind of good news but I this might only be sporadic and I feel that this project should be passed to the community (or other approach) to contribute and evolve this framework, as there is high change that this may be one of the framework that is massively used in many production applications.

**Comment by RubenRibGarcia** [comment]
> The release with Python 3.12 support is on PyPI: https://pypi.org/project/dependency-injector/4.42.0b1/
> 
> ```
> pip install dependency-injector==4.42.0b1
> ```
> 
> Please report any issues you notice by opening an issue here: https://github.com/ets-labs/python-dependency-injector/issues
> 
> I'll publish the plan for future steps a bit later. There is a lot of work to do.

Good news @rmk135 and thank you very much for your comment !

If you need any help/support on this library, I'm willing to help and also contribute

**Comment by rmk135** [comment]
Hi all!

Here's the roadmap for 2024: https://github.com/ets-labs/python-dependency-injector/issues/812

I'll go ahead and close this issue for now.
