### ISSUE TITLE
What is the correct way to set the logger class globally ?

### ISSUE THREAD

**Issue by sh1man** [ets-labs/python-dependency-injector#835]
Where is the best place to insert the line 

logging.setLoggerClass(CustomLoggerClass)

**Comment by ZipFile** [comment]
Closing since this is not exactly related to DI.

<details>

<summary>Meanwhile, check my recipe for logging configuration</summary>

You generally want to initialize logging early in your app lifecycle. With DI I use resources and specific code structure to achieve that:

```python
class Container(DeclarativeContainer):
    ...
    _setup_logging = Resource(
        logging_init,
        level=config.logging.level,
    )
```
Where `logging_init` looks roughly like:
```python
def logging_init(level):
    config = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": level,
        },
    }
    logging.dictConfig(config)
```
Then in your `wsgi.py`/`asgi.py`/`celery.py`/etc you do:
```python
c = Container()
c.init_resources()  # or c._setup_logging.init()
app = c.app()
```
</details>
